version: "3.9"

services:
  api:
    build: .
    container_name: documind-api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./mlruns:/app/mlruns
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    restart: unless-stopped

  streamlit:
    build: .
    container_name: documind-ui
    command: streamlit run app/streamlit_app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./mlruns:/app/mlruns
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    depends_on:
      - api
    restart: unless-stopped

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.11.0
    container_name: documind-mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri /mlflow/mlruns
    restart: unless-stopped
